[package]
name = "postgresql_write"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
postgres = {version = "0.19.2" , features = ["with-serde_json-1", "with-chrono-0_4", "with-time-0_3"] }
